language: python
python:
  - "3.6"
  - "3.7"

sudo: false

branches:
  only:
    - master
    - dev

git:
  depth: 3
# command to install dependencies
install:
  - python -m pip install --user -r requirements.txt
  - python setup.py --user install
# command to run tests
script:
  - pytest

matrix:
  fast_finish: true
