language: python
python:
  - "3.6"
# caches `$HOME/.cache/pip`
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

sudo: false

#branches:
#  only:
#    - master
#    - dev

git:
  depth: 3
# command to install dependencies
install:
  - python -m pip install -r requirements.txt
  - python setup.py install
# command to run tests
before_script:
  - python -m pytest --version
script:
  - python -m pytest

matrix:
  fast_finish: true
